apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nifi-ui-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: nifi-eventproc.npii-aks.dhp-east2us-npe.humana.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: nifi-eventproc
          servicePort: 8080
